spring:
  data:
    mongodb:
      uri: mongodb+srv://username:password@cluster0.s56vqej.mongodb.net/mydatabase?retryWrites=true&w=majority
      database: journaldb
      auto-index-creation: true


server:
  port: 8080
  servlet:
      context-path: /journal


logging:
  level:
    net:
      mehedihasan:
        journalApp: DEBUG